version: "3.9"
services:
  web:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./ForfeitBox
      dockerfile: ./Dockerfile
    ports: -"8000:8000"
