version: "3.9"
services:
  keycloak:
    build:
      context: ./
      dockerfile: ./keycloak.Dockerfile
    ports:
      - "8080:8080"
  web:
    build:
      context: ./
      dockerfile: ./nginx.Dockerfile
    ports:
      - "80:80"
  api:
    build:
      context: ./ForfeitBox
      dockerfile: ./Dockerfile
    ports:
      - "8050:8050"
